version: '3.8'

services:
 web:
  ports:
  - 8000:8000
  entrypoint:
   - ./docker-entrypoint.sh

 pgdb:
  ports:
  - 5432:5432
  environment:
  - POSTGRES_USER=fractals
  - POSTGRES_PASSWORD=fractals
  volumes:
  - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
