version: '3.10'

services:
 web:
  build:
   context: .
  ports:
  - 8000:8000
  volumes:
  - ./:/app

 pgdb:
  image: postgres
  ports:
  - 5433:5432
  environment:
  - POSTGRES_USER=fractals
  - POSTGRES_PASSWORD=fractals
  volumes:
  - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
