name: CI/CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  build_and_docker_hub_push:
    runs-on: ubuntu-latest
    needs: [pre-commit]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fractals-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_docker_hub_push]

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd fractals
          curl -O https://raw.githubusercontent.com/fredoot/fractals/main/docker-compose.base.yml
          curl -O https://raw.githubusercontent.com/fredoot/fractals/main/docker-compose.prod.yml
          docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up --build --force-recreate -d
          docker image prune -f







